version: '3.8'

services:
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # Caddy admin API (metrics)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - monitoring

  frontend:
    image: nginx:latest
    container_name: frontend
    expose:
      - "80"
    ports:
      - "8000:80"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
