services:
  webserver1:
    image: php:apache
    ports:
      - "8000:80"
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - my-network

  webserver2:
    image: php:apache
    ports:
      - "8001:80"
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - my-network

  reverse-proxy:
    image: haproxy:alpine
    ports:
      - "8009:80"
      - "8090:1936"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
